---
#cloud-config

ssh_pwauth: true

groups:
  - osic-lab

users:
  - name: osicer-admin
    # the password is "s3cr3t"
    passwd: $6$rounds=4096$GwqP.JNWz7$qs8DRXMS1ms5gNQzw.vIJtwJshBZ8K/eNKaV0PLA.y4etrFWtV2dUWxQZcZQ2Tk0Mp9uVZMwjF/vehd406v7X.
    lock_passwd: False
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
