---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Check BDD 
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - test-requirements.txt
      - libvirt/**
  pull_request_review:
    types:
      - submitted
jobs:
  check-libvirt-features:
    name: Validate BDD features for libvirt provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # refs/tags/v4.1.7
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # refs/tags/v3.1.1
      - name: generate libvirt terraform plan
        id: plan
        run:
          terraform init
          terraform plan -out=plan.out -target module.libvirt-provider
          terraform show -json plan.out > plan.out.json
      - uses: terraform-compliance/github_action@
        with:
          plan: plan.out.json
          features: features/
