---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Static code analysis checker
# yamllint disable-line rule:truthy
on: 
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  workflow_dispatch:

jobs:
  check-checkov:
    name: Check static code (checkov)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider: [openstack, aws]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # refs/tags/v4.1.7
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@d3328add8f0c9461fb3fe0739296f1cee85f7c2b # refs/tags/v12.2785.0
        with:
          directory: ./${{ matrix.provider }}
          quiet: true
          soft_fail: true
          framework: terraform
          download_external_modules: true
